### ISSUE TITLE
Does not compile with glibc 2.26

### ISSUE THREAD

**Issue by wieczyk** [facebook/facebook-clang-plugins#7]
Hi,

I think something had to be updated since stored clang source code does not compile against glibc 2.26.

```
/tmp/clang-setup.KfT0vO/llvm/projects/compiler-rt/lib/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc:290:22: error: variable has incomplete type 'struct sigaltstack'
```

```
/tmp/clang-setup.KfT0vO/llvm/projects/libcxx/include/__locale:39:11: fatal error: 'xlocale.h' file not found
```

It is known problem:

* https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27xlocale.h.27
* https://reviews.llvm.org/D35697
* https://reviews.llvm.org/D35697
